# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ListWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
import shutil
#import RandomFlashcards

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *


class Ui_Form(QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 261)

        self.importButton = QtWidgets.QPushButton(Form)
        self.importButton.setGeometry(QtCore.QRect(310, 220, 75, 23))
        self.importButton.setObjectName("importButton")
        self.importButton.clicked.connect(self.file_import)

        self.decksList = QtWidgets.QListView(Form)
        self.model = QStandardItemModel(self.decksList)

        self.decksList.clicked['QModelIndex'].connect(self.get_index)

        decksDir = os.listdir("Decks")
        for file in decksDir:
            item = QStandardItem(file)
            self.model.appendRow(item)

        self.decksList.setGeometry(QtCore.QRect(20, 20, 361, 192))
        self.decksList.setObjectName("decksList")
        self.decksList.setModel(self.model)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def get_index(self):
        refr = self.decksList.selectedIndexes()[0]
        print(refr.row())
        print(refr.data())

    def file_import(self):
            # Gets directory (filedir)

        try:
            filedir = QFileDialog.getOpenFileName(self, 'Open File', '/', "CSV files (*.csv)")
            impFile = filedir[0]
            print(impFile)  # creates a savelocation directory

            savelocation = 'Decks'

                # establishes a Decks file for the csv file being imported
            try:
                os.makedirs(savelocation)
                print("Directory ", savelocation, " Created ")
            except FileExistsError:
                print("Directory ", savelocation, " already exists")

            finality = os.path.abspath(savelocation)
            print(finality)
            shutil.copy(impFile, finality)
            print("success")
            splicedName = (os.path.split(impFile)[1])
            print(splicedName)
            self.model.appendRow(QStandardItem(splicedName))
                # crashes the window

        except IOError:
            sys.exit(0)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.importButton.setText(_translate("Form", "Import"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
